# Generated by Django 5.0.6 on 2024-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('FRN', 'FRIENDS'), ('FAM', 'FAMILY'), ('BIZ', 'BUSINESS')], default='FRN', max_length=3),
        ),
    ]
