# Generated by Django 5.0.6 on 2024-06-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_group_name_group_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
