# Generated by Django 5.0.6 on 2024-06-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_group_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='shared_with',
        ),
    ]
